


name: Python movie resource collector from www.dbzyz.com


apis:
  - name: dbzyz
    url: 'http://www.dbzyz.com/inc/dbm3u8.php?ac=videolist&pg={pg}'

database:
  name: mysql
  user: root
  passwd: 123456
  url: localhost
  port: 3306

log:
  pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  file: movies.log


